import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Nav from '../components/Navbar';
import TodoNavbar from '../components/ListNavbar';
import { Button, Text, useTheme } from '@nextui-org/react';
import { Navbar } from "@nextui-org/react";
import { HiMoon } from "react-icons/hi2";
import { Theme } from '@nextui-org/react';
import { BsSunFill } from "react-icons/bs";
import { useTheme as useNextTheme } from 'next-themes'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { type, isDark } = useTheme();
  const { setTheme } = useNextTheme();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar variant="sticky" isBordered>
          <Navbar.Brand>
            <Text h2 size="$5xl">TodoList</Text>
          </Navbar.Brand>
          <Navbar.Content enableCursorHighlight activeColor="secondary" variant="highlight-rounded">
            <Navbar.Link isActive href="#">Features</Navbar.Link>
            <Navbar.Link href="#">Customers</Navbar.Link>
            <Navbar.Link href="#">Pricing</Navbar.Link>
            <Navbar.Link href="#">Company</Navbar.Link>
          </Navbar.Content>
          <Navbar.Content>
            <Button color="gradient" onClick={() => {
              if (isDark === true) {
                setTheme("light")
              }
              else
                setTheme("dark")
            }}>
              {isDark ? <BsSunFill /> : <HiMoon />}
            </Button>
          </Navbar.Content>
        </Navbar>
        <Button size="lg">I am a button</Button>
      </main>
    </>
  )
}
