import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Button, Container, Row, Text, useTheme } from '@nextui-org/react';
import { useTheme as useNextTheme } from 'next-themes'
import TopPart from '../components/TopPart';
import { Card } from '@nextui-org/react';
import ListCard from '../components/List';
import BottomList from '../components/BottomList';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const { type, isDark } = useTheme();
  const { setTheme } = useNextTheme();
  return (
    <>
      <Head>
        <title>TodoList</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Row align='center' justify='center'>
            <TopPart />
          </Row>
          <BottomList />
        </Container>
      </main>
    </>
  )
}
